/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace io.thp.psmove {

public enum Button {
  Btn_TRIANGLE = 1 << 4,
  Btn_CIRCLE = 1 << 5,
  Btn_CROSS = 1 << 6,
  Btn_SQUARE = 1 << 7,
  Btn_SELECT = 1 << 8,
  Btn_START = 1 << 11,
  Btn_PS = 1 << 16,
  Ext_SharpShooter = 1 << 17,
  Btn_MOVE = 1 << 19,
  Btn_T = 1 << 20,
  Btn_WEAPON1 = 1 << 21,
  Btn_WEAPON2 = 1 << 22,
  Btn_WEAPON3 = 1 << 23,
  Btn_SHARPSHOOTER_TRIGGER = 1 << 27,
  Btn_SHARPSHOOTER_RELOAD = 1 << 28
}

}
