/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace io.thp.psmove {

public enum Status {
  Tracker_NOT_CALIBRATED,
  Tracker_CALIBRATION_ERROR,
  Tracker_CALIBRATED,
  Tracker_TRACKING
}

}
